### ISSUE TITLE
Integrate prettier

### ISSUE THREAD

**Issue by ok2ju** [menkuichan/sturdy-umbrella#3]
Task: Integrate prettier

**Comment by menkuichan** [comment]
@ok2ju Should I use this integrating with Eslint?
https://prettier.io/docs/en/integrating-with-linters.html

**Comment by ok2ju** [comment]
Yes, of course

**Comment by ok2ju** [comment]
Resolved in https://github.com/menkuichan/sturdy-umbrella/pull/4
