### ISSUE TITLE
assetPrefix is not defined

### ISSUE THREAD

**Issue by ok2ju** [menkuichan/sturdy-umbrella#5]
Nextjs to properly work on gh-pages should be prefixed with repository name. So, you should use `assetPrefix` property of `nextjs`. See example [here](https://github.com/ok2ju/teleport-components/blob/develop/docs/next.config.js#L18). Also `.nojekyll` file in root of `gh-pages` branch.

**Comment by menkuichan** [comment]
Resolve at gh-pages branch.
